# Generated by Django 4.0 on 2023-05-11 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='placeId',
            field=models.CharField(default='oneid', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='place',
            name='short_title',
            field=models.CharField(default='short', max_length=30),
            preserve_default=False,
        ),
    ]
